package com.launchfleet.backend.featureflags.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.util.List;

import org.junit.jupiter.api.Test;

/**
 * Pure unit tests of FeatureFlag's own invariants - no Spring, no MongoDB. This is
 * the point of moving business rules into the domain: they're testable in isolation.
 */
class FeatureFlagTest {

	@Test
	void booleanFlagGetsTwoAutoGeneratedFixedVariants() {
		FeatureFlag flag = FeatureFlag.create("project-1", "my-flag", "My Flag", null, FlagType.BOOLEAN, null,
				"actor");

		assertThat(flag.getVariants()).hasSize(2);
		assertThat(flag.getVariants()).extracting(Variant::key).containsExactly("false", "true");
		assertThat(flag.getStatus()).isEqualTo(FlagStatus.ACTIVE);
	}

	@Test
	void booleanFlagRejectsCallerSuppliedVariants() {
		List<Variant> requested = List.of(new Variant(null, "x", "X", true, 0));

		assertThatThrownBy(
				() -> FeatureFlag.create("project-1", "my-flag", "My Flag", null, FlagType.BOOLEAN, requested,
						"actor"))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void multivariantFlagRequiresAtLeastTwoVariants() {
		List<Variant> requested = List.of(new Variant(null, "only", "Only", "x", 0));

		assertThatThrownBy(() -> FeatureFlag.create("project-1", "mv-flag", "MV", null, FlagType.MULTIVARIANT,
				requested, "actor")).isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void multivariantFlagRejectsDuplicateVariantKeys() {
		List<Variant> requested = List.of(new Variant(null, "a", "A", 1, 0), new Variant(null, "a", "A2", 2, 1));

		assertThatThrownBy(() -> FeatureFlag.create("project-1", "dup", "Dup", null, FlagType.MULTIVARIANT, requested,
				"actor")).isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void multivariantFlagKeepsCallerSuppliedVariantsInOrder() {
		List<Variant> requested = List.of(new Variant(null, "red", "Red", "#f00", 0),
				new Variant(null, "blue", "Blue", "#00f", 0));

		FeatureFlag flag = FeatureFlag.create("project-1", "theme", "Theme", null, FlagType.MULTIVARIANT, requested,
				"actor");

		assertThat(flag.getVariants()).extracting(Variant::key).containsExactly("red", "blue");
		assertThat(flag.getVariants()).extracting(Variant::order).containsExactly(0, 1);
	}

	@Test
	void creationRequiresAName() {
		assertThatThrownBy(() -> FeatureFlag.create("project-1", "key", " ", null, FlagType.BOOLEAN, null, "actor"))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void retireTransitionsActiveToRetired() {
		FeatureFlag flag = FeatureFlag.create("project-1", "key", "Name", null, FlagType.BOOLEAN, null, "actor");

		flag.retire("actor");

		assertThat(flag.getStatus()).isEqualTo(FlagStatus.RETIRED);
		assertThat(flag.getUpdatedBy()).isEqualTo("actor");
	}

	@Test
	void retiringAnAlreadyRetiredFlagIsRejected() {
		FeatureFlag flag = FeatureFlag.create("project-1", "key", "Name", null, FlagType.BOOLEAN, null, "actor");
		flag.retire("actor");

		assertThatThrownBy(() -> flag.retire("actor")).isInstanceOf(IllegalStateException.class);
	}

	@Test
	void updateMetadataChangesNameAndDescriptionAndStampsActor() {
		FeatureFlag flag = FeatureFlag.create("project-1", "key", "Original", "orig desc", FlagType.BOOLEAN, null,
				"creator");

		flag.updateMetadata("Renamed", "new desc", "editor");

		assertThat(flag.getName()).isEqualTo("Renamed");
		assertThat(flag.getDescription()).isEqualTo("new desc");
		assertThat(flag.getUpdatedBy()).isEqualTo("editor");
	}

	@Test
	void updateMetadataRequiresAName() {
		FeatureFlag flag = FeatureFlag.create("project-1", "key", "Original", null, FlagType.BOOLEAN, null, "actor");

		assertThatThrownBy(() -> flag.updateMetadata("", "desc", "actor"))
				.isInstanceOf(IllegalArgumentException.class);
	}

	@Test
	void defaultVariantIsTheFirstVariant() {
		FeatureFlag flag = FeatureFlag.create("project-1", "key", "Name", null, FlagType.BOOLEAN, null, "actor");

		assertThat(flag.defaultVariant().key()).isEqualTo("false");
	}
}
